version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    groups:
      "test <x-test>test 110</x-test> test":
        applies-to: security-updates
        patterns:
          - certifi
