name: test 127
on:
  workflow_dispatch:
    inputs:
      test:
        description: |-
          **test 127**
          <details open><summary>test 128</summary><b>test 129</b></details>
        required: false
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "${{ inputs.test }}"'
